# Generated by Django 2.1.2 on 2018-10-04 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NecessidadeEspecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=250, null=True, verbose_name='Exibir para todos')),
            ],
        ),
        migrations.CreateModel(
            name='OpcoesAcessibilidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonte_tamanho', models.CharField(blank=True, max_length=250, null=True, verbose_name='Exibir para todos')),
                ('paleta', models.CharField(blank=True, max_length=250, null=True, verbose_name='Exibir para todos')),
                ('legendagem', models.NullBooleanField(max_length=250, verbose_name='Exibir para todos')),
                ('libras', models.NullBooleanField(max_length=250, verbose_name='Exibir para todos')),
                ('ledor', models.NullBooleanField(max_length=250, verbose_name='Exibir para todos')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polo_nome', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nome do pólo')),
                ('polo_codigo', models.CharField(blank=True, max_length=250, null=True, verbose_name='Código do pólo')),
                ('campus_nome', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nome do campus')),
                ('campus_codigo', models.CharField(blank=True, max_length=250, null=True, verbose_name='Código do campus')),
                ('biografia', models.TextField(blank=True, null=True, verbose_name='Biografia')),
                ('email_publico', models.NullBooleanField(verbose_name='Exibir para todos')),
                ('necessidade_especial_publico', models.NullBooleanField(verbose_name='Exibir para todos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
        migrations.CreateModel(
            name='PerfilFoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(upload_to='', verbose_name='Exibir para todos')),
                ('status', models.FileField(upload_to='', verbose_name='Exibir para todos')),
                ('solicitada_em', models.FileField(upload_to='', verbose_name='Exibir para todos')),
                ('homologacao_em', models.FileField(upload_to='', verbose_name='Exibir para todos')),
                ('homologacao_por', models.FileField(upload_to='', verbose_name='Exibir para todos')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilNecessidadeEspecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=250, null=True, verbose_name='Exibir para todos')),
            ],
        ),
    ]
