version: '3.7'

services:

  proxy:
    image: nginx:1.19.2-alpine
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"
    volumes:
      - "../confs/proxy:/etc/nginx/conf.d"
    restart: unless-stopped

  db:
    image: postgres:12.4-alpine
    env_file:
      - ../confs/db.env
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:5432"
    volumes:
      - "../volumes/pgdata:/var/lib/postgresql/data"
      - "./db/initdb_scripts:/docker-entrypoint-initdb.d"
    restart: unless-stopped

  redis:
    image: redis:6.0.8-alpine
    command: redis-server --requirepass redis_password
    restart: unless-stopped

  id:
    image: 'ifrn/suap_ead_base:1.6.2'
    env_file:
      - ../confs/db.env
      - ../confs/suap_ead.env
      - ../confs/id.env
      - ../confs/id_ldap.env
    volumes:
      - '../apps/id:/apps/app'
      - '../libs/:/libs/'
    restart: unless-stopped

  dashboard:
    image: 'ifrn/suap_ead_base:1.6.2'
    env_file:
      - ../confs/db.env
      - ../confs/suap_ead.env
      - ../confs/dashboard.env
    volumes:
      - '../apps/dashboard:/apps/app'
      - '../libs/:/libs/'
    restart: unless-stopped

  pre_matricula:
    image: 'ifrn/suap_ead_base:1.6.2'
    ports:
      - "7001:8000"
    env_file:
      - ../confs/db.env
      - ../confs/suap_ead.env
      - ../confs/pre_matricula.env
    volumes:
      - '../apps/pre_matricula:/apps/app'
      - '../libs/:/libs/'
      - "../volumes/media/pre_matricula:/media/sead/pre_matricula"
    restart: unless-stopped

  agendamento:
    image: 'ifrn/suap_ead_base:1.6.2'
    ports:
      - "7002:8000"
    env_file:
      - ../confs/db.env
      - ../confs/suap_ead.env
      - ../confs/agendamento.env
    volumes:
      - '../apps/agendamento:/apps/app'
      - '../libs/:/libs/'
      - "../volumes/media/agendamento:/media/sead/agendamento"
    restart: unless-stopped

    
  # baggins:
  #   image: 'ifrn/suap_ead_base:1.5.14'
  #   env_file:
  #     - ../confs/db.env
  #     - ../confs/suap_ead.env
  #     - ../confs/baggins.env
  #   volumes:
  #     - '../apps/suap_ead_baggins:/apps/app'
  #     - '../libs/:/libs/'
  #   restart: unless-stopped

  # # c_id:
  # #   image: 'ifrn/suap_ead_base:1.5.14'
  # #   env_file:
  # #     - ../confs/db.env
  # #     - ../confs/suap_ead.env
  # #     - ../confs/c_id.env
  # #   volumes:
  # #     - '../apps/suap_ead_id:/apps/app'
  # #     - '../libs/:/libs/'
  # #   restart: unless-stopped
  
  # # integrador_ui:
  # #   image: 'ifrn/suap_ead_base:1.5.14'
  # #   env_file:
  # #     - ../confs/suap_ead.env
  # #     - ../confs/integrador_ui.env
  # #   volumes:
  # #     - '../apps/suap_ead_integrador_ui:/apps/app'
  # #     - '../libs/:/libs/'
  # #   restart: unless-stopped

  # # seletivo:
  # #   image: 'ifrn/suap_ead_base:1.5.14'
  # #   env_file:
  # #     - ../confs/db.env
  # #     - ../confs/suap_ead.env
  # #     - ../confs/seletivo.env
  # #   volumes:
  # #     - '../apps/suap_ead_seletivo:/apps/app'
  # #     - '../libs/:/libs/'
  # #   restart: unless-stopped

  # # selecao:
  # #   image: 'ifrn/suap_ead_base:1.5.14'
  # #   env_file:
  # #     - ../confs/db.env
  # #     - ../confs/suap_ead.env
  # #     - ../confs/selecao.env
  # #   volumes:
  # #     - '../apps/suap_ead_selecao:/apps/app'
  # #     - '../libs/:/libs/'
  # #   restart: unless-stopped
