#!/bin/bash
source color_logs

echo_info "Stop the world"
./down

echo_info "Reset confs"
rm -rf $EGE_HOME/confs
mkdir $EGE_HOME/confs
cp -r $EGE_HOME/bin/confs_examples/* $EGE_HOME/confs/

echo_info "Reset volumes"
sudo rm -rf $EGE_HOME/volumes

echo_info "Prune system"
docker system prune -a
