#!/bin/bash
source color_logs

echo_info "Reset confs"
rm -rf $SEAD_HOME/confs
mkdir $SEAD_HOME/confs
cp -r $SEAD_HOME/bin/confs_examples/* $SEAD_HOME/confs/

echo_info "Stop the world"
./down

echo_info "Reset volumes"
sudo rm -rf $SEAD_HOME/volumes

echo_info "Prune system"
docker system prune -a
