#!/bin/bash
#
# Deploy the PTD applications.

source env.sh

deploy_django()
{
  echo_info "Deploying $i..."
  ./run $1 migrate
  echo_info "Deployed $i"
}

if [[ $# -ne 0 ]]; then
  SERVICES=($1);
fi

./down
./build
#./init_infra.sh
for i in "${SERVICES[@]}"; do
  deploy_django $i
done
./down
