#!/bin/sh
source functions

USER="admin"
EMAIL="admin@example.com"
PASS="admin"
PY_SCRIPT="from django.contrib.auth.models import User; User.objects.create_superuser('${USER}', '${EMAIL}', '${PASS}')"

./db/up
./$SERVICE_NAME/migrate
echo $PY_SCRIPT | ./$SERVICE_NAME/manage shell
./$SERVICE_NAME/fixtures
