# Generated by Django 2.0.6 on 2018-06-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suapsso', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aplicacaoprotocolo',
            options={'verbose_name': 'Aplicação x Protocólo', 'verbose_name_plural': 'Aplicações x Protocólos'},
        ),
        migrations.AlterModelOptions(
            name='protocolo',
            options={'verbose_name': 'Protocólo', 'verbose_name_plural': 'Protocólos'},
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='nome',
            field=models.CharField(max_length=250, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterUniqueTogether(
            name='aplicacaoprotocolo',
            unique_together={('aplicacao', 'protocolo')},
        ),
    ]
