# Generated by Django 2.1.1 on 2018-09-25 21:00

from django.conf import settings
from django.db import migrations, models
import suap_sso.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
            },
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'Protocolo',
                'verbose_name_plural': 'Protocolos',
            },
        ),
        migrations.CreateModel(
            name='ProtocolApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('application', suap_sso.models.ForeignKey(on_delete=None, to='suap_sso.Application', verbose_name='Application')),
                ('protocol', suap_sso.models.ForeignKey(on_delete=None, to='suap_sso.Protocol', verbose_name='Protocolo')),
            ],
            options={
                'verbose_name': 'Application x Protocol',
                'verbose_name_plural': 'Applications x Protocols',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=250, verbose_name='token')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('expires', models.DateTimeField(verbose_name='expires')),
                ('is_full_permission', models.BooleanField(default=False, verbose_name='is full permission')),
                ('user', suap_sso.models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
            },
        ),
        migrations.CreateModel(
            name='TokenAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', suap_sso.models.ForeignKey(on_delete=None, to='suap_sso.Token', verbose_name='Token')),
            ],
            options={
                'verbose_name': 'Token x User attribute',
                'verbose_name_plural': 'Tokens x User attributes',
            },
        ),
        migrations.CreateModel(
            name='TokenPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', suap_sso.models.ForeignKey(on_delete=None, to='auth.Permission', verbose_name='permission')),
                ('token', suap_sso.models.ForeignKey(on_delete=None, to='suap_sso.Token', verbose_name='Token')),
            ],
            options={
                'verbose_name': 'Token permission',
                'verbose_name_plural': 'Token permissions',
            },
        ),
        migrations.CreateModel(
            name='UserAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
            ],
            options={
                'verbose_name': 'User attribute',
                'verbose_name_plural': 'User attributes',
            },
        ),
        migrations.AddField(
            model_name='tokenattribute',
            name='user_attribute',
            field=suap_sso.models.ForeignKey(on_delete=None, to='suap_sso.UserAttribute', verbose_name='User attribute'),
        ),
        migrations.AlterUniqueTogether(
            name='protocolapplication',
            unique_together={('application', 'protocol')},
        ),
    ]
