# Generated by Django 2.1.2 on 2018-10-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suap_sso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(blank=True, null=True, verbose_name='extensionAttribute10'),
        ),
    ]
