# Generated by Django 2.1.2 on 2018-10-05 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suap_sso', '0002_auto_20181005_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='function',
            new_name='job',
        ),
    ]
