# Generated by Django 2.1.2 on 2018-10-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suap_sso', '0003_auto_20181005_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='extensionAttribute10'),
        ),
    ]
