# Generated by Django 2.1.2 on 2018-10-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suap_sso', '0004_auto_20181005_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='photo',
        ),
        migrations.AddField(
            model_name='usuario',
            name='photo_blob',
            field=models.TextField(blank=True, null=True, verbose_name='thumbnailPhoto'),
        ),
    ]
