# Generated by Django 2.1.2 on 2018-10-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suap_sso', '0005_auto_20181005_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ativo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='extensionAttribute10'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Está ativo?'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='username'),
        ),
    ]
