# Generated by Django 2.1.2 on 2018-10-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suap_sso', '0006_auto_20181005_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fisrt_name',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='givenName'),
        ),
    ]
