# Generated by Django 2.1.2 on 2018-10-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suap_sso', '0007_auto_20181008_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='carreira',
            new_name='carrer',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='enterprise_mail',
            new_name='enterprise_email',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='mail',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='personal mail'),
        ),
    ]
