"""
The MIT License (MIT)

Copyright 2015 Umbrella Tech.
Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
"""

# Generated by Django 2.1.4 on 2018-12-24 21:47

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='givenName')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='sn')),
                ('social_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='social_name')),
                ('department', models.CharField(blank=True, max_length=150, null=True, verbose_name='department')),
                ('campus', models.CharField(blank=True, max_length=150, null=True, verbose_name='extensionAttribute1')),
                ('active', models.CharField(blank=True, max_length=150, null=True, verbose_name='extensionAttribute10')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está ativo?')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='superuser status')),
                ('carrer', models.CharField(blank=True, max_length=150, null=True, verbose_name='extensionAttribute2')),
                ('job', models.CharField(blank=True, max_length=150, null=True, verbose_name='extensionAttribute3')),
                ('cpf', models.CharField(blank=True, max_length=150, null=True, verbose_name='extensionAttribute6')),
                ('academic_email', models.CharField(blank=True, max_length=150, null=True, verbose_name='extensionAttribute4')),
                ('enterprise_email', models.CharField(blank=True, max_length=150, null=True, verbose_name='mail')),
                ('email', models.CharField(blank=True, max_length=150, null=True, verbose_name='personal mail')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='title')),
                ('photo_blob', models.TextField(blank=True, null=True, verbose_name='thumbnailPhoto')),
                ('created_at', models.DateTimeField(blank=True, max_length=150, null=True, verbose_name='whenCreated')),
                ('changed_at', models.DateTimeField(blank=True, max_length=150, null=True, verbose_name='whenChanged')),
                ('password_set_at', models.DateTimeField(blank=True, max_length=150, null=True, verbose_name='pwdLastSet')),
                ('last_access', models.DateTimeField(blank=True, null=True, verbose_name='last access')),
                ('last_ad_access_at', models.DateTimeField(blank=True, null=True, verbose_name='last access')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_access_at', models.DateTimeField(blank=True, null=True, verbose_name='last access')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deletedAt')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['first_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('client_id', models.CharField(max_length=150, verbose_name='client_id')),
                ('secret', models.CharField(max_length=150, verbose_name='client_secret')),
                ('logo', models.FileField(blank=True, null=True, upload_to='', verbose_name='application_logo')),
                ('allowed_callback_urls', models.TextField(blank=True, null=True, verbose_name='allowed_callback_urls')),
                ('allowed_web_origins', models.TextField(blank=True, null=True, verbose_name='allowed_web_origins')),
                ('allowed_logout_urls', models.TextField(blank=True, null=True, verbose_name='allowed_logout_urls')),
                ('expiration', models.PositiveIntegerField(default=300, verbose_name='expiration_in_seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='when_created')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted_at')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'Aplicação',
                'verbose_name_plural': 'Aplicações',
            },
        ),
        migrations.CreateModel(
            name='TransactionToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashcode', models.CharField(max_length=150, verbose_name='hash')),
                ('state', models.CharField(max_length=150, verbose_name='state')),
                ('redirect_uri', models.CharField(max_length=150, verbose_name='redirect_uri')),
                ('referer', models.CharField(max_length=150, verbose_name='referer')),
                ('expire_at', models.DateTimeField(verbose_name='expireAt')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ege_acesso.Application', verbose_name='application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Token de transação',
                'verbose_name_plural': 'Tokens de transações',
            },
        ),
    ]
