# Generated by Django 2.1.4 on 2018-12-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ege_acesso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontoken',
            name='referer',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='referer'),
        ),
    ]
