# Generated by Django 2.1.4 on 2018-12-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ege_acesso', '0002_auto_20181226_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontoken',
            name='hashcode',
            field=models.TextField(verbose_name='hash'),
        ),
        migrations.AlterField(
            model_name='transactiontoken',
            name='redirect_uri',
            field=models.TextField(verbose_name='redirect_uri'),
        ),
        migrations.AlterField(
            model_name='transactiontoken',
            name='referer',
            field=models.TextField(blank=True, null=True, verbose_name='referer'),
        ),
        migrations.AlterField(
            model_name='transactiontoken',
            name='state',
            field=models.TextField(verbose_name='state'),
        ),
    ]
